dist: trusty
language: node_js
cache:
  directories:
    - '~/.npm'
notifications:
  email: false
node_js: '12'
install: echo "install happens as part of setup"
branches:
  only:
    - master
addons:
  sonarcloud:
    organization: edouardr-github
    token:
      secure: jFmpXeYu+r5Ttt+CItvRi6VW3TB7IjurvTucGozyHHNa7LuWLGtV1ZOQ0gPS3cMomujcyYLmt57OECPb9nYrVjJoIGydIUz6nuBEtFLOoEPs068jlF2Jxbnd/IPTfnpfaSOt2syv/8GFPmL5V+D2MpQbvkhaUlvzUm7mdTQir5yNBKxx3N6AdtQDxZr5opRkn2hV1bISvgMRM9HCBjkuFbFKIXB16HkB//3uOsOodEcgNKoWrNjRVsRaj5r4gulLDeggouZBBUg0jTtfJgMbLl3Se2tACOeJjxNBt1vy0BIkwh0uHKpJg3NOcvftnjarbvz+yKQN+aMI9tHRhMGOU42PKBul9NKQHsMdCvjiRlaOY2XRS/U3V8kBDJq5knWY2vSDNpjdmb48/pUiXA6945S4Pr6WcwsKAS9kk876zAKxasEFzwvW3tU75jKVmOntR3X6sFxm1RyLPZ8XgJllaY7GkamgFcw2HH1gfPiYEcY4bwytSdH3xPi36khutL0xbPwc6pdpJCslPOCDrYMOKsgpzm39xPqIUNj56M0fV0prziGbTDPmrT81xhADgZ/CcSXRIpvybcM/v/SjqfRXxZezl1PrdTa5do3SdJJ3tJS3jPxF4WXVwqBQf6gAsP+pkNYyZQje9x5pf2Xd9Qnv1HVQIwCeKIKMEG/6xKOm9LY=
script:
  - npm run setup
  - sonar-scanner
deploy:
  provider: s3
  access_key_id:
    secure: WyeBcOqK2uCQIM1bBXNN8iOP/Of5bN5fk0s2N+QqTmpshBgBdJ9tSjD6k5lLM6SPtcerD8Op+J8hilUx2XQoixcI/vs5KGUjmAry4GRiY//2WXO1l2RYiuCIj9KAp2KLA83YXz143dWgufbt1N5Rl4JKueR9/IM00aFae4pl20AEKfiDj1oYAu89q+wMUudzwIBifd80DfWKk2ZRNxoV03cfP7Fa9Y+xOtP8D7poM6gcmXhrxiiGbNvGG40xjg4zWZ1lYM26zgnNVJhTqvhTebFeCG+WXPHqqGIZMVqWTuxfNOK3TwcxMOmPWvTp8MzSBkkB20MqCgKDn+PODKRYb1WzHfwkpO4R5NZSATIncr0527erp9v/NVAprSdot8N+LmgES0QdI0f/0WWOI+spiPeAzqoWGIQKOBT+16JervnuuUu4G6ekL56f5eapkNwsvg//ud47fhOXQC12fc05U+BQuE6515VxCBE2KOqC9gza6Tj8PPqFh3zT6yiS+HcSPSFQBzJHCxiwcxpdlk0SAiK6fmWicyuF3Szp9tKkbymPFKIROL3Ejp4xeH/3OEivYFclHHKp9djRoqE/fRVD7zg+KCcglP+h+T03GFd007cN1p53bcCPWrvM2i6Byv2KxvHHhMcAEdyMQV5aShHbnkztdb42XgsSgyRnF4zKaLQ=
  secret_access_key:
    secure: jZed8ipm6Yd2TZ0wXOTwEKgEFmJkn3ZTy4n4CvWLbq4MEjV0LXaP+BqLEiTEk1yq0NdBlVxTJyBU/XH9gIzk9aNOtNPcqUX+8fbXB4PE1NpZfAfT+S15oQWNrUr2K/+6ohuDjhaJTHey8tFeZ318LI82yL2lRr8ViCsC5FOz8MGp8yzA+lEHtwSHSh6Z3XrMonRqLrOKIGL9n+nhHvyi7402gBggZRiR9eNCbGEG0FLMppBKM4IlwaGduCwgJ6nFtvz50mI3YVgaLaTqeYN8DmTTDs8SiIMttesz8wkz21fXz75txyWCDTjnmlbx7ubmvSZfPAoyyVxC8IC/7F2k0MONq/YPXbTUSma7/gAdHbXdBh+WA1mASvlBBNO1rTK30mM9DSzBEe9Q0jiyORyOpehtzJ6TMweIXON0BVUmWN4L+1AWSAi5QL9NjjAEDFdw6k6TE0mLzN0G9Wobh22MB/pQvUuTEx9CbMZ/gyZgUy9cRxALf0eBKKkEJy8ds7B9/UpY8TPneHby3NTdDgMGmbjC3CKXDUyO3TPgl1G1Iwa4oilg1kCqL4OYZt0WIliGatHD4JTcK7ytatctgEuHjI/Bjm48W6NjJrE8U4/EMA4QxpSa4Ah+1G7Ksgam3fKz4Z26KbYGB/p/++BkJ2PtSl5zXxl+CoUGAmp5NZp97FI=
  bucket: test-edouardr
  acl: 'public_read'
  local_dir: ./public
  region: eu-west-3
  on:
    repo: edouardr/edouardr.fr
