dist: trusty
language: node_js
cache:
  directories:
    - '~/.npm'
notifications:
  email: false
node_js: '12'
install: echo "install happens as part of setup"
branches:
  only:
    - master
addons:
  sonarcloud:
    organization: edouardr-github
    token:
      secure: jFmpXeYu+r5Ttt+CItvRi6VW3TB7IjurvTucGozyHHNa7LuWLGtV1ZOQ0gPS3cMomujcyYLmt57OECPb9nYrVjJoIGydIUz6nuBEtFLOoEPs068jlF2Jxbnd/IPTfnpfaSOt2syv/8GFPmL5V+D2MpQbvkhaUlvzUm7mdTQir5yNBKxx3N6AdtQDxZr5opRkn2hV1bISvgMRM9HCBjkuFbFKIXB16HkB//3uOsOodEcgNKoWrNjRVsRaj5r4gulLDeggouZBBUg0jTtfJgMbLl3Se2tACOeJjxNBt1vy0BIkwh0uHKpJg3NOcvftnjarbvz+yKQN+aMI9tHRhMGOU42PKBul9NKQHsMdCvjiRlaOY2XRS/U3V8kBDJq5knWY2vSDNpjdmb48/pUiXA6945S4Pr6WcwsKAS9kk876zAKxasEFzwvW3tU75jKVmOntR3X6sFxm1RyLPZ8XgJllaY7GkamgFcw2HH1gfPiYEcY4bwytSdH3xPi36khutL0xbPwc6pdpJCslPOCDrYMOKsgpzm39xPqIUNj56M0fV0prziGbTDPmrT81xhADgZ/CcSXRIpvybcM/v/SjqfRXxZezl1PrdTa5do3SdJJ3tJS3jPxF4WXVwqBQf6gAsP+pkNYyZQje9x5pf2Xd9Qnv1HVQIwCeKIKMEG/6xKOm9LY=
script:
  - npm run setup
  - sonar-scanner
deploy:
  edge: true
  provider: s3
  access_key_id:
    secure: S2QKWDc6p9NVEpGXmnzPkIHcIzkL794gTgnFehuj6xcfa1d7izeWdTrGRqAtENi5YBHQg4Q+0wqYOC7NX5JUc+6e1xZfkx5RFHB9JTxkphpfxx4HamA+byJTgX5KUnOOQj5fI9ciowxRw/BYE3khDnb9wBiRsHR8uu0BUj+RvVPckE4xk+T1WYu1yf8uXI9vgSNonaLM/buyZKzbSaEy/Pxsi3LgaHzLOE0N8fn0W2CsI4cPPA7a9DgFYfzLoOi9t4QsDMDG+MDwaeLOzEm7n5LdJsHcBs++k/cWR7I5/73TDy8XMDDMOZCy9s2VSEqFwAt6H+gJHTSSyUcDrHxzoDi2ACQ/JIdNp2a/rrihxFPpZnz0EuTGXBSrC+0KWRZg16pgv0WgS3WOQVFx+Z8bENDL0LgvJ+e3w8C+0jgIjBQJCwADZ8yu1mJYf3E0d/W6YYH7oZdF+Sawea22scN9DK+ACsBNjQtdqFj2W/b9IWZtRVAtbIwFemWrdroYipYsw1fznkiPxql4lvOUw5eGjQHdwzye+rJpjyXRreIbbU2CwvOLvHQxjHxLXGdNUHL80TbwqDkarA15uVBBYG+MVnGDiA0+8lV/x3NgF7As48AM5ZSJUioNKWjZq62c6PE2VP5JypSOvlz+uGY9XIIx5a1EpSixOAmXXrOw5JN/xZg=
  secret_access_key:
    secure: mDyzYg8ntne8eLKRiIpdNXd2YWQpGzrs6+ofNCi9TKjOkr1y5zbhLnaNdEvAWz64L62jYn3RbYDVPHExE4g31luliqeUNIIcGqC8iohdYUvJYhqyUbWSgh/5HE+acS5hcIuoRW0lMKQ+iEwcaHL8DUghthqLeg4BIWocvAp5EvGp71n23ux4WNOKtMx6LH9DDPc9AlQJk7sdn9EBatpeO4EjmRF21SCnuahuiQLF2IuCIyhnlrGT8IelVJZk18QmQPZ/zFqRLYE/l7x4BOL1qlvOa4AZc7L4toKNcV19ePrhDgeGf0AnUGjhFB57VueEvq459EwwTZ4vFtzuMrbKEVPrsKAe9uPty8EOycURlWgzx+pCHHx5lMMyzc6vUMhBXwLXaE9EXDajv5BdYzzcTxaKIc0AKL+zuTDTbhKwZOpEb2lTlTqib6x9h9pi3gBtfYVIYpTIi6EnVvKOUEMl+vKEn1/QU6GBwHgYUDN5QzHCkcPW2LWuE6Fqob81H+LQxJSvB2XEsNZALjjVoLGqxiyGlvMGM1k1dUO/tr/BtcUX67knihBwcaCpkbPOnzjoJLCwli/NPvNpLgwivbvV6UqgST/E+J6/Dvs33KPCvaQ/noKEWZxtAv0hJ4c6hgpQTbxQc3FXLPL6z4jOUleq46nNB+QfNWDEFp2LhSCn8go=
  bucket: test-edouardr
  acl: 'public_read'
  local_dir: ./public
  skip_cleanup: true
  region: eu-west-3
  on:
    repo: edouardr/edouardr.fr
