dist: trusty
language: node_js
cache:
  directories:
    - '~/.npm'
notifications:
  email: false
node_js: '12'
install:
  - npm install
branches:
  only:
    - master
    - /^release\/.*$/
addons:
  sonarcloud:
    organization: edouardr-github
    token:
      secure: jFmpXeYu+r5Ttt+CItvRi6VW3TB7IjurvTucGozyHHNa7LuWLGtV1ZOQ0gPS3cMomujcyYLmt57OECPb9nYrVjJoIGydIUz6nuBEtFLOoEPs068jlF2Jxbnd/IPTfnpfaSOt2syv/8GFPmL5V+D2MpQbvkhaUlvzUm7mdTQir5yNBKxx3N6AdtQDxZr5opRkn2hV1bISvgMRM9HCBjkuFbFKIXB16HkB//3uOsOodEcgNKoWrNjRVsRaj5r4gulLDeggouZBBUg0jTtfJgMbLl3Se2tACOeJjxNBt1vy0BIkwh0uHKpJg3NOcvftnjarbvz+yKQN+aMI9tHRhMGOU42PKBul9NKQHsMdCvjiRlaOY2XRS/U3V8kBDJq5knWY2vSDNpjdmb48/pUiXA6945S4Pr6WcwsKAS9kk876zAKxasEFzwvW3tU75jKVmOntR3X6sFxm1RyLPZ8XgJllaY7GkamgFcw2HH1gfPiYEcY4bwytSdH3xPi36khutL0xbPwc6pdpJCslPOCDrYMOKsgpzm39xPqIUNj56M0fV0prziGbTDPmrT81xhADgZ/CcSXRIpvybcM/v/SjqfRXxZezl1PrdTa5do3SdJJ3tJS3jPxF4WXVwqBQf6gAsP+pkNYyZQje9x5pf2Xd9Qnv1HVQIwCeKIKMEG/6xKOm9LY=
jobs:
  include:
    - stage: prepare
      script:
        - npm-run-all --parallel type-check format lint

    - stage: test
      script:
        - npm run test
        - sonar-scanner

    - stage: build
      script:
        - npm run build

    - stage: deploy-release
      if: branch =~ /^release\/.*$/
      name: 'Deploy to release S3'
      script: skip
      deploy:
        edge: true
        provider: s3
        upload_dir: $AWS_UPLOAD_DIR_REL
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: $AWS_BUCKET
        local_dir: $AWS_LOCAL_DIR
        region: $AWS_REGION
        verbose: true
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ /^release\/.*$/

    - stage: deploy-production
      if: branch = master
      name: 'Deploy to production S3'
      script: skip
      deploy:
        edge: true
        provider: s3
        upload_dir: $AWS_UPLOAD_DIR
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: $AWS_BUCKET
        local_dir: $AWS_LOCAL_DIR
        region: $AWS_REGION
        verbose: true
        on:
          branch: master
