dist: trusty
language: node_js
before_cache:
  - pip install --user awscli
cache:
  directories:
    - '~/.npm'
notifications:
  email: false
node_js: '12'
before_install:
  - npm install -g @lhci/cli@0.3.x awss3-deploy
install: echo "install happens as part of setup"
branches:
  only:
    - master
    - /^release\/.*$/
    - develop
addons:
  sonarcloud:
    organization: edouardr-github
    token:
      secure: jFmpXeYu+r5Ttt+CItvRi6VW3TB7IjurvTucGozyHHNa7LuWLGtV1ZOQ0gPS3cMomujcyYLmt57OECPb9nYrVjJoIGydIUz6nuBEtFLOoEPs068jlF2Jxbnd/IPTfnpfaSOt2syv/8GFPmL5V+D2MpQbvkhaUlvzUm7mdTQir5yNBKxx3N6AdtQDxZr5opRkn2hV1bISvgMRM9HCBjkuFbFKIXB16HkB//3uOsOodEcgNKoWrNjRVsRaj5r4gulLDeggouZBBUg0jTtfJgMbLl3Se2tACOeJjxNBt1vy0BIkwh0uHKpJg3NOcvftnjarbvz+yKQN+aMI9tHRhMGOU42PKBul9NKQHsMdCvjiRlaOY2XRS/U3V8kBDJq5knWY2vSDNpjdmb48/pUiXA6945S4Pr6WcwsKAS9kk876zAKxasEFzwvW3tU75jKVmOntR3X6sFxm1RyLPZ8XgJllaY7GkamgFcw2HH1gfPiYEcY4bwytSdH3xPi36khutL0xbPwc6pdpJCslPOCDrYMOKsgpzm39xPqIUNj56M0fV0prziGbTDPmrT81xhADgZ/CcSXRIpvybcM/v/SjqfRXxZezl1PrdTa5do3SdJJ3tJS3jPxF4WXVwqBQf6gAsP+pkNYyZQje9x5pf2Xd9Qnv1HVQIwCeKIKMEG/6xKOm9LY=
  chrome: stable
script:
  - npm run setup
  - sonar-scanner
after_success:
  - lhci autorun
before_deploy:
  - export BUCKET=$AWS_BUCKET LOCAL_DIR=$AWS_LOCAL_DIR
    UPLOAD_DIR=$AWS_UPLOAD_DIR
  - |
    if [[ $TRAVIS_BRANCH =~ ^release\/.*$ ]]; then
      export UPLOAD_DIR=$AWS_UPLOAD_DIR_REL
    fi
deploy:
  - if: ($TRAVIS_BRANCH =~ /^release\/.*$/) OR ($TRAVIS_BRANCH = master)
    provider: script
    script: awss3-deploy
    edge: true
    on:
      all_branches: true
